apiVersion: v1
kind: Service
metadata:
  name: measurements-service
spec:
  selector:
    app: measurements
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
