apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patients
  template:
    metadata:
      labels:
        app: patients
    spec:
      containers:
        - name: patients
          image: patients:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "your-database-url"
