apiVersion: v1
kind: Service
metadata:
  name: patients-service
spec:
  selector:
    app: patients
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
